#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PREFIX=${HERE}/usr
export LD_LIBRARY_PATH=${HERE}/usr/lib${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
export PYTHONHOME=${HERE}/usr
# export QT_QPA_PLATFORM_PLUGIN_PATH=${HERE}/usr/plugins
# export QT_XKB_CONFIG_ROOT=${HERE}/usr/lib
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts
# export QTWEBENGINEPROCESS_PATH=${HERE}/usr/libexec/QtWebEngineProcess

# Show packages info if DEBUG env variable is set
if [ "$DEBUG" = 1 ]; then
    cat ${HERE}/packages.txt
fi

# Delete cached .qhc file if DOC env variable is set
# https://github.com/FreeCAD/FreeCAD-AppImage/issues/25
if [ "$DOC" = 1 ]; then
    if [ -e "$HOME/.local/share/freecad/freecad/freecad.qhc" ]; then
        rm $HOME/.local/share/freecad/freecad/freecad.qhc
        echo "AppImage: DOC environment variable was set."
        echo "AppImage: $HOME/.local/share/freecad/freecad/freecad.qhc was deleted."
    fi
fi

# SSL
# https://forum.freecadweb.org/viewtopic.php?f=4&t=34873&start=20#p327416
export SSL_CERT_FILE=$PREFIX/ssl/cacert.pem
# https://github.com/FreeCAD/FreeCAD-AppImage/pull/20
export GIT_SSL_CAINFO=$HERE/usr/ssl/cacert.pem

# Support for launching other applications (from /usr/bin)
# https://github.com/FreeCAD/FreeCAD-AppImage/issues/30
if [ ! -z "$1" ] && [ -e "$HERE/usr/bin/$1" ] ; then
    MAIN="$HERE/usr/bin/$1" ; shift
else
    MAIN="$HERE/usr/bin/freecad"
fi

${MAIN} "$@"
