#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
echo ${HERE}
export PREFIX=$HERE/usr
export LD_LIBRARY_PATH=$HERE/usr/lib
export PYTHONHOME=$HERE/usr
export QT_QPA_PLATFORM_PLUGIN_PATH=$HERE/usr/plugins
export QT_XKB_CONFIG_ROOT=$HERE/usr/lib
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts

# Delete cached .qhc file if DOC env variable is set
# https://github.com/FreeCAD/FreeCAD-AppImage/issues/25
if [ "$DOC" = 1 ]; then
    if [ -e "$HOME/.local/share/freecad/freecad/freecad.qhc" ]; then
        rm $HOME/.local/share/freecad/freecad/freecad.qhc
        echo "AppImage: DOC environment variable was set."
        echo "AppImage: $HOME/.local/share/freecad/freecad/freecad.qhc was deleted."
    fi
fi

# SSL
# https://forum.freecadweb.org/viewtopic.php?f=4&t=34873&start=20#p327416
export SSL_CERT_FILE=$PREFIX/ssl/cacert.pem
# https://github.com/FreeCAD/FreeCAD-AppImage/pull/20
export GIT_SSL_CAINFO=$HERE/usr/ssl/cacert.pem

${HERE}/usr/bin/FreeCAD "$@"
