#!/usr/bin/env bash
HERE=$(dirname "$(dirname "$0")")
PREFIX=$HERE/Resources
export LD_LIBRARY_PATH=$PREFIX/lib
export PYTHONHOME=$PREFIX
export QT_QPA_PLATFORM_PLUGIN_PATH=$PREFIX/plugins
export QT_XKB_CONFIG_ROOT=$PREFIX/lib
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts
$PREFIX/bin/FreeCAD $@